### ISSUE TITLE
请教：中文编写代码的经验和问题

### ISSUE THREAD

**Issue by nobodxbodon** [gasolin/zhpy#35]
您好，最近在总结一些用中文编写代码的资料和项目， 其中一个主要问题是[代码风格](https://github.com/nobodxbodon/program-in-chinese/issues/2#issuecomment-279254451)。想请问在开发周蟒的过程中，有可以分享的经验吗？
另外，这里是一个假想的[适合中文开发的编程语言和开发环境](https://github.com/nobodxbodon/nextProgrammingLanguageForChinese)，列出了一些必需的特性，希望得到您的批评和建议。

**Comment by gasolin** [comment]
因為周蟒是由Python轉譯，所以完全依照Python編程風格。這麼做的好處是很容易與Python接軌。在取用外部函式或需要遷移時可以更快上手。

**Comment by nobodxbodon** [comment]
关于命名规范, 看到[周蟒的建议](https://code.google.com/archive/p/zhpy/wikis/CodingStyle.wiki)是:

> 變量和函數的命名並沒有強制的規則，不過可以試著使用"類"(class)以"名詞"命名，"方法"(method)，函式(function)以動詞命名的規則。

那么比如常量(根据[PEP 8 -- Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)需要全大写), 如果中文命名的话, 就需要其他办法区分了吧?
