### ISSUE TITLE
Py 3.6.3 macOS installed but not working

### ISSUE THREAD

**Issue by ZoomQuiet** [gasolin/zhpy#36]
## install
my env.

    ༄  python
    Python 3.6.3 (default, Oct 16 2017, 20:59:30)
    [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.

- got https://github.com/gasolin/zhpy/archive/master.zip
- and enter `zhpy3`
- `python setup.py install`

    ༄  pip show zhpy3
    Name: zhpy3
    Version: 3.0.0a1
    Summary: Write python(3) language in chinese
    Home-page: http://zhpy.googlecode.com/
    Author: Fred Lin
    Author-email: gasolin+zhpy@gmail.com
    License: Type license() to see the full license text
    Location: /Users/zoomq/.pyenv/versions/3.6.3/envs/gc363/lib/python3.6/site-packages/zhpy3-3.0.0a1-py3.6.egg
    Requires: setuptools
    Required-by:

## error

- but there is not `zhpy` or `zhpy3` can running...
- what happen?

**Comment by gasolin** [comment]
zhpy is only compatible with 2.x now.... Welcome to port zhpy to python 3 if it makes sense

**Comment by ZoomQuiet** [comment]
@gasolin 是也乎,(￣▽￣)

got it ;-(

**Comment by nobodxbodon** [comment]
@ZoomQuiet 恰巧看到, 之前在[OBP](https://groups.google.com/forum/#!topic/openbookproject/NZG5LJfkj9I)多谢指点. 请问你打算做Python中文化的尝试吗? 我们[组里](https://github.com/program-in-chinese/overview)会有兴趣做一些相关工具, 比如IDE支持等等.

**Comment by ZoomQuiet** [comment]
Xuan Wu <notifications@github.com> 于2018年10月17日周三 下午5:05写道：

> @ZoomQuiet <https://github.com/ZoomQuiet> 恰巧看到, 之前在OBP
> <https://groups.google.com/forum/#!topic/openbookproject/NZG5LJfkj9I>多谢指点.
> 请问你打算做Python中文化的尝试吗? 我们组里 <https://github.com/program-in-chinese/overview>会有兴趣做一些相关工具,
> 比如IDE支持等等.
>
>
嗯哼, 这种好事儿, 直接邮件沟通吧...
不应该将 gh-issue 当成 BBS 聊天的...

-- 
life is pathetic, go Pythonic! 人生苦短, Python当歌!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization learning!

**Comment by ZoomQuiet** [comment]
@absente 是也乎,(￣▽￣)

[GitHub的中国乱象：刷星、高仿、骂街和版聊, PingWest品玩](https://mp.weixin.qq.com/s/xCn9a8FRCgu_sdm7NM--dA)

简单说, 不是规定, 而是文化气质不匹配,
如果是购买的私人/公司仓库, 在内部你怎么来都成, 
但是, 这是公开仓库, 你也注意到, 俺尽可能用 english 来描述问题,
就是因为, 这样可以获得更多的反馈...

但是, 你在这儿直接用中文, 并进行 out topic 的交流, 
就完全违反了这个 Issue 创建的初衷, 是种....任性?

CANCEL for overflow ;-( 放弃/转义/过期....

**Comment by ZoomQuiet** [comment]
CANCEL for overflow ;-( 放弃/转义/过期....
